### ISSUE TITLE
OSError: [Errno 123] getWindowsLongPathName for c:\progra~2\\bcrypt.dll (文件名、目录名或卷标语法不正确。)

### ISSUE THREAD

**Issue by milaogou** [yllhwa/decrypt-mflac-frida#1]
'''Y:\Git\decrypt-mflac-frida>nuitka --standalone --onefile --lto=yes --output-dir=out hook_qq_music.py
Nuitka-Options: Used command line options: --standalone --onefile --lto=yes --output-dir=out hook_qq_music.py
Nuitka: Starting Python compilation with Nuitka '2.1rc3' on Python '3.11' commercial grade 'not installed'.
Nuitka-Plugins:anti-bloat: Not including 'socket' automatically in order to avoid bloat, but this may cause: can break
Nuitka-Plugins:anti-bloat: calls of 'email.utils.make_msgid()'.
Nuitka: Completed Python level compilation and optimization.
Nuitka: Generating source code for C backend compiler.
Nuitka: Running data composer tool for optimal constant value handling.
Nuitka: Running C compilation via Scons.
Nuitka-Scons: Backend C compiler: gcc (gcc 13.2.0).
Nuitka-Scons: Backend linking program with 6 files (no progress information available for this stage).
Nuitka-Scons: Compiled 6 C files using ccache.
Nuitka-Scons: Cached C files (using ccache) with result 'cache miss': 6
Nuitka-Reports: Compilation report written to file 'nuitka-crash-report.xml'.
Detecting used DLLs: 14.3%|███▌                     | 1/7, hook_qq_music.exeTraceback (most recent call last):
  File "C:\Users\Administrator\AppData\Roaming\Python\Python311\site-packages\nuitka\__main__.py", line 175, in <module>
    main()
  File "C:\Users\Administrator\AppData\Roaming\Python\Python311\site-packages\nuitka\__main__.py", line 161, in main
    MainControl.main()
  File "C:\Users\Administrator\AppData\Roaming\Python\Python311\site-packages\nuitka\MainControl.py", line 1130, in main
    _main()
  File "C:\Users\Administrator\AppData\Roaming\Python\Python311\site-packages\nuitka\MainControl.py", line 1022, in _main
    detectUsedDLLs(
  File "C:\Users\Administrator\AppData\Roaming\Python\Python311\site-packages\nuitka\freezer\Standalone.py", line 335, in detectUsedDLLs
    _detectUsedDLLs(
  File "C:\Users\Administrator\AppData\Roaming\Python\Python311\site-packages\nuitka\freezer\Standalone.py", line 253, in _detectUsedDLLs
    used_dlls = _detectBinaryDLLs(
                ^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\AppData\Roaming\Python\Python311\site-packages\nuitka\freezer\Standalone.py", line 142, in _detectBinaryDLLs
    return detectBinaryPathDLLsWin32(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\AppData\Roaming\Python\Python311\site-packages\nuitka\freezer\DllDependenciesWin32.py", line 97, in detectBinaryPathDLLsWin32
    result = detectDLLsWithDependencyWalker(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\AppData\Roaming\Python\Python311\site-packages\nuitka\freezer\DependsExe.py", line 232, in detectDLLsWithDependencyWalker
    result = parseDependsExeOutput(output_filename)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\AppData\Roaming\Python\Python311\site-packages\nuitka\freezer\DependsExe.py", line 173, in parseDependsExeOutput
    return _parseDependsExeOutput2(getFileContentByLine(filename, encoding="latin1"))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\AppData\Roaming\Python\Python311\site-packages\nuitka\freezer\DependsExe.py", line 147, in _parseDependsExeOutput2
    dll_filename = getWindowsLongPathName(dll_filename)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\AppData\Roaming\Python\Python311\site-packages\nuitka\utils\FileOperations.py", line 1151, in getWindowsLongPathName
    raiseWindowsError("getWindowsLongPathName for %s" % filename)
  File "C:\Users\Administrator\AppData\Roaming\Python\Python311\site-packages\nuitka\utils\Utils.py", line 410, in raiseWindowsError
    raise WindowsError(
OSError: [Errno 123] getWindowsLongPathName for c:\progra~2\\bcrypt.dll (文件名、目录名或卷标语法不正确。)
Nuitka-Reports: Compilation crash report written to file 'nuitka-crash-report.xml'. Please include it in your bug report.'''
![image](https://github.com/yllhwa/decrypt-mflac-frida/assets/130544843/51aa7b22-2415-4d85-aa7b-16d3d17d391f)

**Comment by milaogou** [comment]
删除报错处这个dll文件即可（我是直接卸载了这个应用程序，因为这个应用程序是中文目录）
