### ISSUE TITLE
`home`变量必须是绝对路径

### ISSUE THREAD

**Issue by virtualxiaoman** [yllhwa/decrypt-mflac-frida#5]
一个小问题哈，主要是怕其他人也犯一样的错误然后以为工具不能用了

`home`必须是绝对路径，不然会报错：
```
frida.core.RPCException: Error: invalid size
    at value (frida/runtime/core.js:194)
    at decrypt (/script1.js:73)
    at call (native)
    at <anonymous> (frida/runtime/message-dispatcher.js:11)
    at o (frida/runtime/message-dispatcher.js:23)
```
加个`home = os.path.abspath(home)`即可

**Comment by ShakeWeLy** [comment]
我把音乐改到E盘了 
`# 获取用户音乐目录路径
home = "E:\_MUSIC\\VipSongsDownload"
home = os.path.abspath(home)
`
这么处理报错了
`Decrypting 24kGoldn _ Justin Bieber _ J Balvin _ iann dior - Mood (Remix_Explicit).mgg
Traceback (most recent call last):
  File "F:\Git_iteam\QQ音乐decrypt-mflac-frida-main\hook_qq_music.py", line 47, in <module>
    data = script.exports_sync.decrypt(os.path.join(root, file), tmp_file_path)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Pydata\anacondai\Lib\site-packages\frida\core.py", line 180, in method
    return script._rpc_request(request, data, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Pydata\anacondai\Lib\site-packages\frida\core.py", line 86, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "D:\Pydata\anacondai\Lib\site-packages\frida\core.py", line 497, in _rpc_request
    raise result.error
frida.core.RPCException: Error: No such file or directory
    at decrypt (/script1.js:79)
    at call (native)
    at <anonymous> (frida/runtime/message-dispatcher.js:11)
    at o (frida/runtime/message-dispatcher.js:23)`

**Comment by virtualxiaoman** [comment]
注意到`Error: No such file or directory at decrypt`，你的路径确实是`home = "E:\_MUSIC\\VipSongsDownload"`吗？MUSIC前面有`_`这个符号吗？另外建议使用`/`作为路径的分隔符，你可以尝试在调用js代码前print一下路径看看有没有问题，我之前是因为使用相对路径会报类似的错误所以要改成绝对路径。

**Comment by ShakeWeLy** [comment]
谢谢你 我把音乐文件位置复原 重新尝试可以了

**Comment by baba990aini** [comment]
upup，thanks！
